services:
  development:
    #     # userns_mode: "keep-id"
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
        USR: frontend
    volumes:
      - ./:/home/frontend/project
#     environment:
#       - NODE_ENV=development
#       - API_URL=http://backend:8080
#     ports:
#       - "2233:22"
#       - "3000:3000"

#   production:
#     # userns_mode: "keep-id"
#     build:
#       context: .
#       target: production
#       args:
#         UID: ${UID}
#         GID: ${GID}
#         USR: frontend
#     environment:
#       - NODE_ENV=production
#     ports:
#       - "3000:3000"
#     profiles:
#       - production
