services:
  development:
    # userns_mode: "keep-id"
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/home/user/frontend
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8080
    ports:
      - '3000:3000'
      - '53000:53000'
    profiles:
      - development

  production:
    # userns_mode: "keep-id"
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8080
    ports:
      - '3000:3000'
    profiles:
      - production
