services:
  frontend:
    build:
      context: ..
      target: production
      dockerfile: docker/dockerfile
    platform: linux/amd64
    environment:
      - API_URL=${API_URL}
    ports:
      - '3000:3000'
    restart: unless-stopped
